### PR TITLE
Updated everything. Welcome to 2020.

### PR DESCRIPTION
**Pull request by phdoerfler**
I rarely mess with sbt plugins so buyers beware, but the travis command line runs fine on my machine so there's hoping.
I'm not 100% sure about the many `crossSbtVersions`. it's probably overkill and only having 0.13 and 1.3 would be sufficient.
The version of the plugin itself might also want to be bumped up to a 3.2 or a 4 given the quantity of the changes.

### CODE REVIEW

**Comment by soc** [comment]
Seems to fail on the CI with:
```
error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
```

**Comment by phdoerfler** [comment]
I am not sure what to make of the CI error. Off the top of my head I can only think of having run JDK 8 locally whereas Travis used JDK 11. It's as vague a suspicion as it gets but I will try and see if that makes a difference locally.

**Comment by phdoerfler** [comment]
This does indeed make a difference and I can reproduce the error locally using openjdk11 instead of oracle jdk 8. How very annoying.

**Comment by phdoerfler** [comment]
fwiw: I have returned from a longer vacation and will look into this again in the next days.

**Comment by phdoerfler** [comment]
The PR's title is showing its age, time to finish it. Speaking of time: I'm cautiously optimistic that I can do so soon:tm:

**Comment by PenghaiZhang** [comment]
> The PR's title is showing its age, time to finish it. Speaking of time: I'm cautiously optimistic that I can do so soon

It's almost 2 years old. Do you know any alternative of this plugin ?

**Comment by SethTisue** [comment]
sbt 0.13 support should be removed to keep things simple

**Comment by phdoerfler** [comment]
I agree, 0.13 has outstayed its welcome. But IIRC that's not the issue here, the CI failed because of some hardcoded path that needs to be changed.
@PenghaiZhang I don't think there is an alternative to this plugin. Working on this issue is the next thing in my backlog, but my current task at work takes priority I'm afraid.

**Comment by phdoerfler** [comment]
I'm closing this PR. It doesn't look like I'll be able to make much progress on this in the near future and even if then it's likely better to restart from scratch.

**Pull request closed without merging**
